/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShortcutExpenseRouteImport } from './routes/shortcut-expense'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiProxySplatRouteImport } from './routes/api-proxy.$'
import { Route as AppTripsRouteImport } from './routes/_app.trips'
import { Route as AppShortcutsRouteImport } from './routes/_app.shortcuts'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppNewTripRouteImport } from './routes/_app.new-trip'
import { Route as AppNewExpenseRouteImport } from './routes/_app.new-expense'
import { Route as AppMealsRouteImport } from './routes/_app.meals'
import { Route as AppExpensesRouteImport } from './routes/_app.expenses'
import { Route as AppTripsIdRouteImport } from './routes/_app.trips.$id'
import { Route as AppAdminUsersRouteImport } from './routes/_app.admin.users'

const ShortcutExpenseRoute = ShortcutExpenseRouteImport.update({
  id: '/shortcut-expense',
  path: '/shortcut-expense',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProxySplatRoute = ApiProxySplatRouteImport.update({
  id: '/api-proxy/$',
  path: '/api-proxy/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTripsRoute = AppTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => AppRoute,
} as any)
const AppShortcutsRoute = AppShortcutsRouteImport.update({
  id: '/shortcuts',
  path: '/shortcuts',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNewTripRoute = AppNewTripRouteImport.update({
  id: '/new-trip',
  path: '/new-trip',
  getParentRoute: () => AppRoute,
} as any)
const AppNewExpenseRoute = AppNewExpenseRouteImport.update({
  id: '/new-expense',
  path: '/new-expense',
  getParentRoute: () => AppRoute,
} as any)
const AppMealsRoute = AppMealsRouteImport.update({
  id: '/meals',
  path: '/meals',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesRoute = AppExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppTripsIdRoute = AppTripsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppTripsRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/shortcut-expense': typeof ShortcutExpenseRoute
  '/expenses': typeof AppExpensesRoute
  '/meals': typeof AppMealsRoute
  '/new-expense': typeof AppNewExpenseRoute
  '/new-trip': typeof AppNewTripRoute
  '/profile': typeof AppProfileRoute
  '/shortcuts': typeof AppShortcutsRoute
  '/trips': typeof AppTripsRouteWithChildren
  '/api-proxy/$': typeof ApiProxySplatRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/trips/$id': typeof AppTripsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/shortcut-expense': typeof ShortcutExpenseRoute
  '/expenses': typeof AppExpensesRoute
  '/meals': typeof AppMealsRoute
  '/new-expense': typeof AppNewExpenseRoute
  '/new-trip': typeof AppNewTripRoute
  '/profile': typeof AppProfileRoute
  '/shortcuts': typeof AppShortcutsRoute
  '/trips': typeof AppTripsRouteWithChildren
  '/api-proxy/$': typeof ApiProxySplatRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/trips/$id': typeof AppTripsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/shortcut-expense': typeof ShortcutExpenseRoute
  '/_app/expenses': typeof AppExpensesRoute
  '/_app/meals': typeof AppMealsRoute
  '/_app/new-expense': typeof AppNewExpenseRoute
  '/_app/new-trip': typeof AppNewTripRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/shortcuts': typeof AppShortcutsRoute
  '/_app/trips': typeof AppTripsRouteWithChildren
  '/api-proxy/$': typeof ApiProxySplatRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/trips/$id': typeof AppTripsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/shortcut-expense'
    | '/expenses'
    | '/meals'
    | '/new-expense'
    | '/new-trip'
    | '/profile'
    | '/shortcuts'
    | '/trips'
    | '/api-proxy/$'
    | '/admin/users'
    | '/trips/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/shortcut-expense'
    | '/expenses'
    | '/meals'
    | '/new-expense'
    | '/new-trip'
    | '/profile'
    | '/shortcuts'
    | '/trips'
    | '/api-proxy/$'
    | '/admin/users'
    | '/trips/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/shortcut-expense'
    | '/_app/expenses'
    | '/_app/meals'
    | '/_app/new-expense'
    | '/_app/new-trip'
    | '/_app/profile'
    | '/_app/shortcuts'
    | '/_app/trips'
    | '/api-proxy/$'
    | '/_app/admin/users'
    | '/_app/trips/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ShortcutExpenseRoute: typeof ShortcutExpenseRoute
  ApiProxySplatRoute: typeof ApiProxySplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shortcut-expense': {
      id: '/shortcut-expense'
      path: '/shortcut-expense'
      fullPath: '/shortcut-expense'
      preLoaderRoute: typeof ShortcutExpenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-proxy/$': {
      id: '/api-proxy/$'
      path: '/api-proxy/$'
      fullPath: '/api-proxy/$'
      preLoaderRoute: typeof ApiProxySplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/trips': {
      id: '/_app/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof AppTripsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shortcuts': {
      id: '/_app/shortcuts'
      path: '/shortcuts'
      fullPath: '/shortcuts'
      preLoaderRoute: typeof AppShortcutsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/new-trip': {
      id: '/_app/new-trip'
      path: '/new-trip'
      fullPath: '/new-trip'
      preLoaderRoute: typeof AppNewTripRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/new-expense': {
      id: '/_app/new-expense'
      path: '/new-expense'
      fullPath: '/new-expense'
      preLoaderRoute: typeof AppNewExpenseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/meals': {
      id: '/_app/meals'
      path: '/meals'
      fullPath: '/meals'
      preLoaderRoute: typeof AppMealsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expenses': {
      id: '/_app/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AppExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/trips/$id': {
      id: '/_app/trips/$id'
      path: '/$id'
      fullPath: '/trips/$id'
      preLoaderRoute: typeof AppTripsIdRouteImport
      parentRoute: typeof AppTripsRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppTripsRouteChildren {
  AppTripsIdRoute: typeof AppTripsIdRoute
}

const AppTripsRouteChildren: AppTripsRouteChildren = {
  AppTripsIdRoute: AppTripsIdRoute,
}

const AppTripsRouteWithChildren = AppTripsRoute._addFileChildren(
  AppTripsRouteChildren,
)

interface AppRouteChildren {
  AppExpensesRoute: typeof AppExpensesRoute
  AppMealsRoute: typeof AppMealsRoute
  AppNewExpenseRoute: typeof AppNewExpenseRoute
  AppNewTripRoute: typeof AppNewTripRoute
  AppProfileRoute: typeof AppProfileRoute
  AppShortcutsRoute: typeof AppShortcutsRoute
  AppTripsRoute: typeof AppTripsRouteWithChildren
  AppAdminUsersRoute: typeof AppAdminUsersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppExpensesRoute: AppExpensesRoute,
  AppMealsRoute: AppMealsRoute,
  AppNewExpenseRoute: AppNewExpenseRoute,
  AppNewTripRoute: AppNewTripRoute,
  AppProfileRoute: AppProfileRoute,
  AppShortcutsRoute: AppShortcutsRoute,
  AppTripsRoute: AppTripsRouteWithChildren,
  AppAdminUsersRoute: AppAdminUsersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ShortcutExpenseRoute: ShortcutExpenseRoute,
  ApiProxySplatRoute: ApiProxySplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
