/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTripsRouteImport } from './routes/_app.trips'
import { Route as AppTripsIdRouteImport } from './routes/_app.trips.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTripsRoute = AppTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => AppRoute,
} as any)
const AppTripsIdRoute = AppTripsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppTripsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/trips': typeof AppTripsRouteWithChildren
  '/trips/$id': typeof AppTripsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/trips': typeof AppTripsRouteWithChildren
  '/trips/$id': typeof AppTripsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/trips': typeof AppTripsRouteWithChildren
  '/_app/trips/$id': typeof AppTripsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/trips' | '/trips/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/trips' | '/trips/$id'
  id: '__root__' | '/' | '/_app' | '/login' | '/_app/trips' | '/_app/trips/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/trips': {
      id: '/_app/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof AppTripsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/trips/$id': {
      id: '/_app/trips/$id'
      path: '/$id'
      fullPath: '/trips/$id'
      preLoaderRoute: typeof AppTripsIdRouteImport
      parentRoute: typeof AppTripsRoute
    }
  }
}

interface AppTripsRouteChildren {
  AppTripsIdRoute: typeof AppTripsIdRoute
}

const AppTripsRouteChildren: AppTripsRouteChildren = {
  AppTripsIdRoute: AppTripsIdRoute,
}

const AppTripsRouteWithChildren = AppTripsRoute._addFileChildren(
  AppTripsRouteChildren,
)

interface AppRouteChildren {
  AppTripsRoute: typeof AppTripsRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppTripsRoute: AppTripsRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
